### ISSUE TITLE
TODO: release "installer" docker image

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#806]
It would be useful to release a cni docker image with the plugins. It would be even more awesome if it was signed with chainguard / cosign.

It could either be based on alpine / busybox so that it includes `cp`, or go distroless for use as a base image.

Just need to figure out how to do multiarch docker builds.

- [ ] Dockerfile to build CNI plugins. Bonus points for playing nice with dependabot.
- [ ] Multiarch Dockerfile for released "installer" image
- [ ] Fixup `release.sh` to use this (or some equivalent)
- [ ] Build releases automatically via GitHub and push them to ghcr
- [ ] Cosign all the things!

**Comment by EmilyShepherd** [comment]
I have a distroless container version for the dhcp / bridge plugins here: https://github.com/EmilyShepherd/kiOS/tree/main/pkgs/images/dhcp-cni. It's multiarch (amd64 and arm64 with musl and a small init binary for copying the binaries) 

At the moment this is fairly coupled to the wider project it's part of, but I'd be happy to take some learnings of this to contribute a more generalised build if that would be helpful 😊

**Comment by squeed** [comment]
@EmilyShepherd heck yeah, feel free. And don't worry about getting everything all done at once.

Also, nothing in `release.sh` is sacred; change whatever you need to make it work.

**Comment by yashsingh74** [comment]
@squeed can I help in any of the given open items.
Happy to help.

**Comment by squeed** [comment]
@yashsingh74 please feel free! @EmilyShepherd, have you found any time :-)?

**Comment by EmilyShepherd** [comment]
Sorry I have been distracted by other things - happy for you to look at this @yashsingh74

**Comment by yashsingh74** [comment]
Thanks, I will work on it then.

**Comment by leojonathanoh** [comment]
Hey guys, I managed to get multiarch working, based on work in #245. Should I open a new PR or reopen #245?

**Comment by yashsingh74** [comment]
great @leojonathanoh.
I am also working on it. But if you already have the code ready. Please go ahead.

**Comment by leojonathanoh** [comment]
It will be good to see your work too, maybe you might have solved it better. I haven't done cosign yet, not very familiar with it.

**Comment by yashsingh74** [comment]
@leojonathanoh please raise the PR. I will also see if I can do better on it.
Thanks :)

**Comment by leojonathanoh** [comment]
Alright, will do :)
